# Generated by Django 4.2 on 2025-04-30 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('account_update', models.DateField(auto_now=True)),
                ('account_status', models.BooleanField(default=True)),
                ('account_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_name', models.TextField()),
                ('card_descrip', models.TextField(blank=True)),
                ('card_progress', models.TextField(blank=True)),
                ('colour_code', models.TextField(blank=True)),
                ('card_red_vote', models.IntegerField(blank=True, default=0)),
                ('card_yellow_vote', models.IntegerField(blank=True, default=0)),
                ('card_green_vote', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_engineer', models.BooleanField(default=False)),
                ('is_team_leader', models.BooleanField(default=False)),
                ('is_department_leader', models.BooleanField(default=False)),
                ('is_senior_manager', models.BooleanField(default=False)),
                ('role_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_name', models.TextField()),
                ('session_started', models.DateTimeField()),
                ('session_deleted', models.DateTimeField(blank=True, null=True)),
                ('session_status', models.TextField()),
            ],
            options={
                'ordering': ['-session_started'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('vote_value', models.CharField(max_length=20)),
                ('vote_opinion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_check.card')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_check.session')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_check.department')),
            ],
            options={
                'ordering': ['team_name'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('overall_health_rating', models.TextField()),
                ('health_start_date', models.DateField()),
                ('health_end_date', models.DateField()),
                ('progress_over_time', models.TextField()),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_check.card')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_check.department')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_check.team')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_check.team'),
        ),
        migrations.AddField(
            model_name='card',
            name='session_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_check.session'),
        ),
        migrations.AddField(
            model_name='user',
            name='Account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='health_check.account'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_check.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_check.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_check.team'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission'),
        ),
    ]
