# Generated by Django 5.1.7 on 2025-03-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_check', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
    ]
