# Generated by Django 5.2 on 2025-04-28 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='session_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_check.session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
