# Generated by Django 4.2 on 2025-04-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_check', '0002_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='green_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='red_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='yellow_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_choice',
            field=models.CharField(choices=[('Red', 'Unsatisfied'), ('Yellow', 'Partially Satisfied'), ('Green', 'Satisfied')], max_length=10),
        ),
    ]
