# Generated by Django 5.2 on 2025-04-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_check', '0002_session_session_name_alter_card_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_name',
            field=models.TextField(),
        ),
    ]
