# Generated by Django 5.1.7 on 2025-03-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_check', '0002_remove_role_user'),
    ]

    operations = [
    ]
