# Generated by Django 5.1.7 on 2025-04-13 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('health_check', '0003_auto_20250330_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.TextField()),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_started', models.DateTimeField()),
                ('session_deleted', models.DateTimeField()),
                ('session_status', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='is_department_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_team_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health_check.account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_name', models.TextField()),
                ('card_green_vote', models.IntegerField()),
                ('card_red_vote', models.IntegerField()),
                ('card_yellow_vote', models.IntegerField()),
                ('card_descrip', models.TextField()),
                ('card_progress', models.TextField()),
                ('colour_code', models.TextField()),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_check.session')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_check.department')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('overall_health_rating', models.TextField()),
                ('health_start_date', models.DateField()),
                ('health_end_date', models.DateField()),
                ('progress_over_time', models.TextField()),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_check.card')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_check.department')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_check.team')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_check.team'),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_check.team'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('vote_value', models.TextField()),
                ('vote_opinion', models.TextField()),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_check.card')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_check.session')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_check.user')),
            ],
        ),
    ]
