# Generated by Django 4.2 on 2025-04-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_check', '0003_card_green_votes_card_red_votes_card_yellow_votes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='reason',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
