<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-04-16 17:09
=======
# Generated by Django 5.1.6 on 2025-04-16 15:34
>>>>>>> origin/test-branch

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_check', '0004_department_session_account_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_check.role'),
        ),
    ]
