# Generated by Django 4.2 on 2025-04-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_check', '0004_alter_vote_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('engineer', 'Engineer'), ('team_leader', 'Team Leader'), ('dept_leader', 'Department Leader'), ('senior_manager', 'Senior Manager')], default='engineer', max_length=20),
        ),
    ]
