# Generated by Django 5.2 on 2025-04-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_check', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_green_vote',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_progress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_red_vote',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_yellow_vote',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='colour_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_deleted',
            field=models.DateTimeField(blank=True),
        ),
    ]
