# Generated by Django 4.2 on 2025-04-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_check', '0006_team_user_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='When the session happens')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
            ],
        ),
    ]
