# Generated by Django 4.2 on 2025-04-28 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_check', '0007_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_check.session'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_choice',
            field=models.CharField(choices=[('red', 'Unsatisfied'), ('yellow', 'Partially Satisfied'), ('green', 'Satisfied')], max_length=10),
        ),
    ]
