# Generated by Django 4.2 on 2025-04-29 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_check', '0008_vote_session_alter_vote_vote_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['department__name', 'name']},
        ),
        migrations.AlterField(
            model_name='team',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='health_check.department'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'department')},
        ),
    ]
